/* 
 * Weather API
 *
 * # Introduction WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy. We provide following data through our API:     - Real-time weather - 14 day weather forecast - Historical Weather - Marine Weather and Tide Data - Future Weather (Upto 365 days ahead) - Daily and hourly intervals - 15 min interval (Enterprise only) - Astronomy - Time zone - Location data - Sports - Search or Autocomplete API - Weather Alerts - Air Quality Data - Bulk Request  # Getting Started    You need to [signup](https://www.weatherapi.com/signup.aspx) and then you can find your API key under [your account](https://www.weatherapi.com/login.aspx), and start using API right away!  Try our weather API by using interactive [API Explorer](https://www.weatherapi.com/api-explorer.aspx).  We also have SDK for popular framework/languages available on [Github](https://github.com/weatherapicom/) for quick integrations.  If you find any features missing or have any suggestions, please [contact us](https://www.weatherapi.com/contact.aspx).    # Authentication    API access to the data is protected by an API key. If at anytime, you find the API key has become vulnerable, please regenerate the key using Regenerate button next to the API key.    Authentication to the WeatherAPI.com API is provided by passing your API key as request parameter through an API .      ##  key parameter  key=YOUR API KEY  
 *
 * OpenAPI spec version: 1.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AstronomyAstro
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AstronomyAstroTests
    {
        // TODO uncomment below to declare an instance variable for AstronomyAstro
        //private AstronomyAstro instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AstronomyAstro
            //instance = new AstronomyAstro();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AstronomyAstro
        /// </summary>
        [Test]
        public void AstronomyAstroInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AstronomyAstro
            //Assert.IsInstanceOfType<AstronomyAstro> (instance, "variable 'instance' is a AstronomyAstro");
        }


        /// <summary>
        /// Test the property 'Sunrise'
        /// </summary>
        [Test]
        public void SunriseTest()
        {
            // TODO unit test for the property 'Sunrise'
        }
        /// <summary>
        /// Test the property 'Sunset'
        /// </summary>
        [Test]
        public void SunsetTest()
        {
            // TODO unit test for the property 'Sunset'
        }
        /// <summary>
        /// Test the property 'Moonrise'
        /// </summary>
        [Test]
        public void MoonriseTest()
        {
            // TODO unit test for the property 'Moonrise'
        }
        /// <summary>
        /// Test the property 'Moonset'
        /// </summary>
        [Test]
        public void MoonsetTest()
        {
            // TODO unit test for the property 'Moonset'
        }
        /// <summary>
        /// Test the property 'MoonPhase'
        /// </summary>
        [Test]
        public void MoonPhaseTest()
        {
            // TODO unit test for the property 'MoonPhase'
        }
        /// <summary>
        /// Test the property 'MoonIllumination'
        /// </summary>
        [Test]
        public void MoonIlluminationTest()
        {
            // TODO unit test for the property 'MoonIllumination'
        }

    }

}
