/* 
 * Weather API
 *
 *  # Introduction  WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy.   We provide following data through our API:    * Real-time weather<br />    * 14 day weather forecast<br />    * Astronomy<br />    * Time zone<br />    * Location data<br />    * Search or Autocomplete API<br />    * NEW: Historical weather      * NEW: Future Weather (Upto 300 days ahead)      * Weather Alerts      * Air Quality Data  # Getting Started  You need to [signup](https://www.weatherapi.com/signup.aspx) and then you can find your API key under [your account](https://www.weatherapi.com/login.aspx), and start using API right away!  We have [code libraries](https://www.weatherapi.com/docs/code-libraries.aspx) for different programming languages like PHP, .net, JAVA, etc.  If you find any features missing or have any suggestions, please [contact us](https://www.weatherapi.com/contact.aspx).  # Authentication  API access to the data is protected by an API key. If at anytime, you find the API key has become vulnerable, please regenerate the key using Regenerate button next to the API key.  Authentication to the WeatherAPI.com API is provided by passing your API key as request parameter through an API .    ##  key parameter   key=\\<YOUR API KEY\\> 
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ForecastAstro
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ForecastAstroTests
    {
        // TODO uncomment below to declare an instance variable for ForecastAstro
        //private ForecastAstro instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ForecastAstro
            //instance = new ForecastAstro();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ForecastAstro
        /// </summary>
        [Test]
        public void ForecastAstroInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ForecastAstro
            //Assert.IsInstanceOfType<ForecastAstro> (instance, "variable 'instance' is a ForecastAstro");
        }


        /// <summary>
        /// Test the property 'Sunrise'
        /// </summary>
        [Test]
        public void SunriseTest()
        {
            // TODO unit test for the property 'Sunrise'
        }
        /// <summary>
        /// Test the property 'Sunset'
        /// </summary>
        [Test]
        public void SunsetTest()
        {
            // TODO unit test for the property 'Sunset'
        }
        /// <summary>
        /// Test the property 'Moonrise'
        /// </summary>
        [Test]
        public void MoonriseTest()
        {
            // TODO unit test for the property 'Moonrise'
        }
        /// <summary>
        /// Test the property 'Moonset'
        /// </summary>
        [Test]
        public void MoonsetTest()
        {
            // TODO unit test for the property 'Moonset'
        }
        /// <summary>
        /// Test the property 'MoonPhase'
        /// </summary>
        [Test]
        public void MoonPhaseTest()
        {
            // TODO unit test for the property 'MoonPhase'
        }
        /// <summary>
        /// Test the property 'MoonIllumination'
        /// </summary>
        [Test]
        public void MoonIlluminationTest()
        {
            // TODO unit test for the property 'MoonIllumination'
        }

    }

}
