/* 
 * Weather API
 *
 *  # Introduction  WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy.   We provide following data through our API:    * Real-time weather<br />    * 14 day weather forecast<br />    * Astronomy<br />    * Time zone<br />    * Location data<br />    * Search or Autocomplete API<br />    * NEW: Historical weather      * NEW: Future Weather (Upto 300 days ahead)      * Weather Alerts      * Air Quality Data  # Getting Started  You need to [signup](https://www.weatherapi.com/signup.aspx) and then you can find your API key under [your account](https://www.weatherapi.com/login.aspx), and start using API right away!  We have [code libraries](https://www.weatherapi.com/docs/code-libraries.aspx) for different programming languages like PHP, .net, JAVA, etc.  If you find any features missing or have any suggestions, please [contact us](https://www.weatherapi.com/contact.aspx).  # Authentication  API access to the data is protected by an API key. If at anytime, you find the API key has become vulnerable, please regenerate the key using Regenerate button next to the API key.  Authentication to the WeatherAPI.com API is provided by passing your API key as request parameter through an API .    ##  key parameter   key=\\<YOUR API KEY\\> 
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ForecastHour
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ForecastHourTests
    {
        // TODO uncomment below to declare an instance variable for ForecastHour
        //private ForecastHour instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ForecastHour
            //instance = new ForecastHour();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ForecastHour
        /// </summary>
        [Test]
        public void ForecastHourInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ForecastHour
            //Assert.IsInstanceOfType<ForecastHour> (instance, "variable 'instance' is a ForecastHour");
        }


        /// <summary>
        /// Test the property 'TimeEpoch'
        /// </summary>
        [Test]
        public void TimeEpochTest()
        {
            // TODO unit test for the property 'TimeEpoch'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'TempC'
        /// </summary>
        [Test]
        public void TempCTest()
        {
            // TODO unit test for the property 'TempC'
        }
        /// <summary>
        /// Test the property 'TempF'
        /// </summary>
        [Test]
        public void TempFTest()
        {
            // TODO unit test for the property 'TempF'
        }
        /// <summary>
        /// Test the property 'IsDay'
        /// </summary>
        [Test]
        public void IsDayTest()
        {
            // TODO unit test for the property 'IsDay'
        }
        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Test]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }
        /// <summary>
        /// Test the property 'WindMph'
        /// </summary>
        [Test]
        public void WindMphTest()
        {
            // TODO unit test for the property 'WindMph'
        }
        /// <summary>
        /// Test the property 'WindKph'
        /// </summary>
        [Test]
        public void WindKphTest()
        {
            // TODO unit test for the property 'WindKph'
        }
        /// <summary>
        /// Test the property 'WindDegree'
        /// </summary>
        [Test]
        public void WindDegreeTest()
        {
            // TODO unit test for the property 'WindDegree'
        }
        /// <summary>
        /// Test the property 'WindDir'
        /// </summary>
        [Test]
        public void WindDirTest()
        {
            // TODO unit test for the property 'WindDir'
        }
        /// <summary>
        /// Test the property 'PressureMb'
        /// </summary>
        [Test]
        public void PressureMbTest()
        {
            // TODO unit test for the property 'PressureMb'
        }
        /// <summary>
        /// Test the property 'PressureIn'
        /// </summary>
        [Test]
        public void PressureInTest()
        {
            // TODO unit test for the property 'PressureIn'
        }
        /// <summary>
        /// Test the property 'PrecipMm'
        /// </summary>
        [Test]
        public void PrecipMmTest()
        {
            // TODO unit test for the property 'PrecipMm'
        }
        /// <summary>
        /// Test the property 'PrecipIn'
        /// </summary>
        [Test]
        public void PrecipInTest()
        {
            // TODO unit test for the property 'PrecipIn'
        }
        /// <summary>
        /// Test the property 'Humidity'
        /// </summary>
        [Test]
        public void HumidityTest()
        {
            // TODO unit test for the property 'Humidity'
        }
        /// <summary>
        /// Test the property 'Cloud'
        /// </summary>
        [Test]
        public void CloudTest()
        {
            // TODO unit test for the property 'Cloud'
        }
        /// <summary>
        /// Test the property 'FeelslikeC'
        /// </summary>
        [Test]
        public void FeelslikeCTest()
        {
            // TODO unit test for the property 'FeelslikeC'
        }
        /// <summary>
        /// Test the property 'FeelslikeF'
        /// </summary>
        [Test]
        public void FeelslikeFTest()
        {
            // TODO unit test for the property 'FeelslikeF'
        }
        /// <summary>
        /// Test the property 'WindchillC'
        /// </summary>
        [Test]
        public void WindchillCTest()
        {
            // TODO unit test for the property 'WindchillC'
        }
        /// <summary>
        /// Test the property 'WindchillF'
        /// </summary>
        [Test]
        public void WindchillFTest()
        {
            // TODO unit test for the property 'WindchillF'
        }
        /// <summary>
        /// Test the property 'HeatindexC'
        /// </summary>
        [Test]
        public void HeatindexCTest()
        {
            // TODO unit test for the property 'HeatindexC'
        }
        /// <summary>
        /// Test the property 'HeatindexF'
        /// </summary>
        [Test]
        public void HeatindexFTest()
        {
            // TODO unit test for the property 'HeatindexF'
        }
        /// <summary>
        /// Test the property 'DewpointC'
        /// </summary>
        [Test]
        public void DewpointCTest()
        {
            // TODO unit test for the property 'DewpointC'
        }
        /// <summary>
        /// Test the property 'DewpointF'
        /// </summary>
        [Test]
        public void DewpointFTest()
        {
            // TODO unit test for the property 'DewpointF'
        }
        /// <summary>
        /// Test the property 'WillItRain'
        /// </summary>
        [Test]
        public void WillItRainTest()
        {
            // TODO unit test for the property 'WillItRain'
        }
        /// <summary>
        /// Test the property 'ChanceOfRain'
        /// </summary>
        [Test]
        public void ChanceOfRainTest()
        {
            // TODO unit test for the property 'ChanceOfRain'
        }
        /// <summary>
        /// Test the property 'WillItSnow'
        /// </summary>
        [Test]
        public void WillItSnowTest()
        {
            // TODO unit test for the property 'WillItSnow'
        }
        /// <summary>
        /// Test the property 'ChanceOfSnow'
        /// </summary>
        [Test]
        public void ChanceOfSnowTest()
        {
            // TODO unit test for the property 'ChanceOfSnow'
        }
        /// <summary>
        /// Test the property 'VisKm'
        /// </summary>
        [Test]
        public void VisKmTest()
        {
            // TODO unit test for the property 'VisKm'
        }
        /// <summary>
        /// Test the property 'VisMiles'
        /// </summary>
        [Test]
        public void VisMilesTest()
        {
            // TODO unit test for the property 'VisMiles'
        }
        /// <summary>
        /// Test the property 'GustMph'
        /// </summary>
        [Test]
        public void GustMphTest()
        {
            // TODO unit test for the property 'GustMph'
        }
        /// <summary>
        /// Test the property 'GustKph'
        /// </summary>
        [Test]
        public void GustKphTest()
        {
            // TODO unit test for the property 'GustKph'
        }
        /// <summary>
        /// Test the property 'Uv'
        /// </summary>
        [Test]
        public void UvTest()
        {
            // TODO unit test for the property 'Uv'
        }

    }

}
